import { Analytics } from "@vercel/analytics/next";
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";
import "./globals.css";

const sackersGothic = localFont({
  variable: "--font-sackersgothic",
  src: [
    {
      path: "./fonts/sackers-gothic/Sackers-Gothic-Light.woff2",
      weight: "300",
    },
    {
      path: "./fonts/sackers-gothic/Sackers-Gothic-Medium.woff2",
      weight: "400",
    },
    {
      path: "./fonts/sackers-gothic/Sackers-Gothic-Heavy.woff2",
      weight: "700",
    },
  ],
  subsets: ["latin"],
});

const bickhamScript = localFont({
  variable: "--font-bickhamscript",
  src: [
    {
      path: "./fonts/bickham-script/BickhamScriptPro-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/bickham-script/BickhamScriptPro-Semibold.woff2",
      weight: "600",
    },
    {
      path: "./fonts/bickham-script/BickhamScriptPro-Bold.woff2",
      weight: "700",
    },
  ],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="h-dvh">
      <body
        className={`${sackersGothic.className} ${sackersGothic.variable} ${bickhamScript.variable} antialiased h-dvh bg-secondary text-primary`}
      >
        <NavBar />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
